uploads = []
generated = []

[[outputs]]
id = "OVY1vn5HVFG_nNGTI1b0_"
uri = "file://artifacts/desktop/dist-electron/UnitEconomics-win-x64.zip"
type = "unspecified"
title = "Unit Economics — Windows x64 (портативная версия)"

[[outputs]]
id = "Pa6NUvuQ-Rl00G-l9xeDs"
uri = "file://artifacts/ozon-unit-economics/public/UnitEconomics-win-x64-v2.zip"
type = "unspecified"
title = "UnitEconomics-win-x64-v2.zip (Десктоп, новая версия)"

[[outputs]]
id = "4wcgE7vpHFhDxid2BCiow"
uri = "file://artifacts/desktop/dist-electron/UnitEconomics-win-x64-v2.zip"
type = "unspecified"
title = "UnitEconomics-win-x64-v2.zip — с фильтром, итогами, М/закуп."

[[outputs]]
id = "MhIInyJ0FvusyIohBYCCP"
uri = "file://db_dump.pgdump.gz"
type = "unspecified"
title = "База данных (db_dump.pgdump.gz)"
