import { Router, type IRouter } from "express";
import authRouter from "./auth";
import healthRouter from "./health";
import settingsRouter from "./settings";
import productsRouter from "./products";
import campaignsRouter from "./campaigns";
import keywordsRouter from "./keywords";
import experimentsRouter from "./experiments";
import dashboardRouter from "./dashboard";
import importRouter from "./import";
import ymRouter from "./ym";
import ymApiRouter from "./ym-api";
import ozonRouter from "./ozon";
import ozonApiRouter from "./ozon-api";
import ozonSalesRouter from "./ozon-sales";
import ymCpmRouter from "./ym-cpm";
import skuCardRouter from "./sku-card";
import ozonLiveRouter from "./ozon-live";
import wbLiveRouter from "./wb-live";
import wbRouter from "./wb";
import ymLiveRouter from "./ym-live";
import ordersFeedRouter from "./orders-feed";
import stocksRouter from "./stocks";
import shipmentPlanRouter from "./shipment-plan";
import shipmentsRouter from "./shipments";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(settingsRouter);
router.use(productsRouter);
router.use(campaignsRouter);
router.use(keywordsRouter);
router.use(experimentsRouter);
router.use(dashboardRouter);
router.use(importRouter);
router.use(ymRouter);
router.use(ymApiRouter);
router.use(ozonRouter);
router.use(ozonApiRouter);
router.use(ozonSalesRouter);
router.use(ymCpmRouter);
router.use(skuCardRouter);
router.use(ozonLiveRouter);
router.use(wbLiveRouter);
router.use(wbRouter);
router.use(ymLiveRouter);
router.use(ordersFeedRouter);
router.use(stocksRouter);
router.use(shipmentPlanRouter);
router.use(shipmentsRouter);

export default router;
