// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ue-redesign/CleanLight.tsx": () => import("../components/mockups/ue-redesign/CleanLight.tsx"),
  "./components/mockups/ue-redesign/VividLight.tsx": () => import("../components/mockups/ue-redesign/VividLight.tsx")
};
